### ISSUE TITLE
Separate form layout and form styling SCSS files

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-forms#229]
### Describe your feature request

![image](https://user-images.githubusercontent.com/41635034/168105878-9d79ac05-7847-4543-b7d5-a803dede6998.png)

When disabling default forms styles we are also disabling a lot of useful layout styles like form field width, .etc
It would be great if we could separate layout styles in a new stylesheet that can also have a toggle. 

### Describe the solution you'd like

Separate form layout stylesheet from general form styles (colors, borders, active states).

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
great idea but no, because the plugin will not be responsible for providing or breaking styles in the clients project. If you choose to use the plugin styles you accept the risk of stuff breaking, if you want to provide your own styles you should do that, but combining plugin styles and project styles sounds like a bad idea to me.
